---
abstract: 'Offset a Lat/Long in Google Maps'
author:
  - 'Iftekharul Haque <iftekhar@cpan.org>'
build_requires:
  Data::Printer: 0
  Test::Simple: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.023, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-GoogleMaps-OffsetCenter
requires:
  Exporter::Easy: 0
  Math::Trig: 0
  Params::Validate: 0
  Regexp::Common: 0
  constant: 0
  strict: 0
  warnings: 0
version: 0.04
